---
title: "Step 1 Examination"
date: 2019-06-25
output: html_notebook
---

```{r global_stuff, include=FALSE}

# TODO
# - 

library(Luminescence)
library(numOSL)
library(OSLdecomposition)
library(knitr)

knitr::opts_chunk$set(fig.width=10, 
                      fig.asp=.6, 
                      warning=FALSE,
                      error=FALSE,
                      echo=FALSE)
```

IMPORTANT: Load Workspace "Step1" before proceeding

```{r}

#data_entry <- list(name = "",global.curve = data.frame(NULL), fit.overview = data.frame(NULL))


# Number of aliquots:
# Batagai   20
# BK8       20
# Oy7       20
# BT594     24
# BT1214    30
# BT1240    48



# Data set dependend parameters
max_number_of_components <- 5

### Which sample ?? ###

GC <- Batagai

```






```{r}

global_components <- fit_OSLcurve(global_curve,
                                  algorithm = "streched",
                                  N.allowed = c(1:max_number_of_components),
                                  significance.threshold = 0.1,
                                  stimulation.intensity = 30)

```

